services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: uae-travel-migrate
    env_file:
      - ./app.env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["go", "run", "migrate/migrate.go", "seed"]

volumes:
  postgres:
